done

diff --git a/.github/workflows/CICD_Main.yml b/.github/workflows/CICD_Main.yml
--- a/.github/workflows/CICD_Main.yml
+++ b/.github/workflows/CICD_Main.yml
@@ -8,70 +8,70 @@ on:
 
 jobs:
 
-  Unit-Testing-Main:
-    runs-on: ubuntu-latest
-    outputs:
-      test-passed: ${{ steps.test-step.outputs.test-passed }}
+  # Unit-Testing-Main:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     test-passed: ${{ steps.test-step.outputs.test-passed }}
 
-    steps:
-      - name: Checkout Main Branch
-        uses: actions/checkout@v4
-        with:
-          ref: main
+  #   steps:
+  #     - name: Checkout Main Branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: main
 
-      - name: Setup Node environment
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: 'npm'
+  #     - name: Setup Node environment
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
+  #         cache: 'npm'
       
-      - name: Install dependencies
-        run: npm install
+  #     - name: Install dependencies
+  #       run: npm install
 
-      - name: Run tests
-        id: test-step
-        run: |
-          npm run test
-          if [ $? -eq 0 ]; then
-            echo "test-passed=success" >> "$GITHUB_OUTPUT"
-            echo "All unit testing Passed!" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "test-passed=failure" >> "$GITHUB_OUTPUT"
-            echo "Unit testing failed!" >> $GITHUB_STEP_SUMMARY
-          fi
+  #     - name: Run tests
+  #       id: test-step
+  #       run: |
+  #         npm run test
+  #         if [ $? -eq 0 ]; then
+  #           echo "test-passed=success" >> "$GITHUB_OUTPUT"
+  #           echo "All unit testing Passed!" >> $GITHUB_STEP_SUMMARY
+  #         else
+  #           echo "test-passed=failure" >> "$GITHUB_OUTPUT"
+  #           echo "Unit testing failed!" >> $GITHUB_STEP_SUMMARY
+  #         fi
 
-  trivy-scan-for-vulnerabilities:
-    runs-on: ubuntu-latest
-    outputs:
-      trivy-result: ${{ steps.trivy-result-step.outputs.result }}
+  # trivy-scan-for-vulnerabilities:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     trivy-result: ${{ steps.trivy-result-step.outputs.result }}
     
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
       
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
 
-      - name: Run Trivy scanner
-        id: trivy-result-step
-        uses: aquasecurity/trivy-action@0.20.0
-        with:
-          scan-type: fs
-          hide-progress: true
-          output: trivy.txt
+  #     - name: Run Trivy scanner
+  #       id: trivy-result-step
+  #       uses: aquasecurity/trivy-action@0.20.0
+  #       with:
+  #         scan-type: fs
+  #         hide-progress: true
+  #         output: trivy.txt
 
-      - name: Publish Trivy Output to Summary
-        run: |
-          echo "### Security Output" >> $GITHUB_STEP_SUMMARY
-          echo "<details><summary>Click to expand</summary>" >> $GITHUB_STEP_SUMMARY
-          echo "" >> $GITHUB_STEP_SUMMARY
-          echo '```terraform' >> $GITHUB_STEP_SUMMARY
-          cat trivy.txt >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
-          echo "</details>" >> $GITHUB_STEP_SUMMARY
+  #     - name: Publish Trivy Output to Summary
+  #       run: |
+  #         echo "### Security Output" >> $GITHUB_STEP_SUMMARY
+  #         echo "<details><summary>Click to expand</summary>" >> $GITHUB_STEP_SUMMARY
+  #         echo "" >> $GITHUB_STEP_SUMMARY
+  #         echo '```terraform' >> $GITHUB_STEP_SUMMARY
+  #         cat trivy.txt >> $GITHUB_STEP_SUMMARY
+  #         echo '```' >> $GITHUB_STEP_SUMMARY
+  #         echo "</details>" >> $GITHUB_STEP_SUMMARY
 
   # Sonarqube-Code-analysis:
   #   runs-on: ubuntu-latest
@@ -102,14 +102,12 @@ jobs:
   docker-image-build-and-push:
     # needs: [Unit-Testing-Main, trivy-scan-for-vulnerabilities, Sonarqube-Code-analysis]
     # if: needs.Unit-Testing-Main.outputs.test-passed == 'success' && needs.Sonarqube-Code-analysis.outputs.quality-gate-status == 'PASSED'
-    needs: Unit-Testing-Main
+    # needs: Unit-Testing-Main
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-        with:
-          ref: main
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
@@ -128,4 +126,4 @@ jobs:
         with:
           context: .
           push: true
-          tags: neranjanhub/agromart:latest
+          tags: neranjanhub/agromart:latest ,neranjanhub/agromart:${{github.run_number}}
